example_project/example_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # needed so we can serve media while DEBUG=True

example_project/users/urls.py
from functools import partial

from django.conf.urls import url
from django.contrib.auth import views as auth_views


from . import views


app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.CustomSocialLoginView.as_view(), name='login'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^logout/$', partial(auth_views.logout, template_name='logout.html'), name='logout'),
]

example_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField()

example_project/users/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django_social_pill.utils import unlink_appropriate_account


class CustomSocialLoginView(TemplateView):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('users:profile')
        return super().get(request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

    def post(self, request, *args, **kwargs):
        unlink_appropriate_account(self.request.user, self.request)
        return redirect(reverse('users:profile'))

example_project/users/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock title %}</title>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous" media="none" onload="if(media!='all')media='all'">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" media="none" onload="if(media!='all')media='all'"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.min.css" media="none" onload="if(media!='all')media='all'"/>
</head>
<body>
  {% block content %}{% endblock content %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>

example_project/users/templates/login.html
{% extends 'base.html' %}

{% load social_login %}

{% block title %}Вход{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row text-center" style="margin-bottom: 15px; margin-top: 50px;">
      <h1>Привет!</h1>
      <div>Давай знакомиться.</div>
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
          <div>{{ message }}</div>
        {% endif %}
      {% endfor %}
      {# Note that the error messages will be raplaced by exceptions while DEBUG = True #}
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div style="color: darkred">{{ message }}</div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="row col-sm-4 col-sm-offset-4">
      {% show_vk_login request.path True True %}
    </div>
    <div class="row col-sm-4 col-sm-offset-4" style="margin-top: 10px;">
      {% show_twitter_login request.path True False %}
    </div>
    <div class="col-sm-4 col-sm-offset-4 centered" style="margin-top: 30px;">
      Мы&nbsp;не&nbsp;просим лишних прав доступа и&nbsp;не&nbsp;дадим никому твой&nbsp;аккаунт.
    </div>
  </div>
{% endblock content %}

example_project/users/templates/logout.html
{% extends 'base.html' %}

{% block title %}Выход{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row text-center">
      <h1>Пока!</h1>
      <div><a href="{% url 'users:login' %}">Заходи</a>, если что.</div>
    </div>
  </div>
{% endblock content %}

example_project/users/templates/profile.html
{% extends 'base.html' %}

{% load social_connect %}

{% block title %}Профиль{% endblock title %}

{% block content %}
  <div class="row text-center" style="margin-top: 30px;">
    <img src="{{ user.avatar.url }}" width=100 height=100>
  </div>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="col-sm-6 col-sm-offset-3">
        {% show_vk_connect request.path user %}
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-6 col-sm-offset-3">
        {% show_twitter_connect request.path user %}
      </div>
    </div>
  </form>
  <div class="row text-center">
    {# Note that the error messages will be raplaced by exceptions while DEBUG = True #}
    {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div style="color: darkred">{{ message }}</div>
      {% endif %}
    {% endfor %}
  </div>
  <div class="row text-center">
    <a href="{% url 'users:logout' %}">Выйти</a>
  </div>
{% endblock content %}